# Generated by Django 3.2.8 on 2021-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='desc1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
